# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'windows-2019'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: |
    cd netDumbster
    dotnet publish --framework "netstandard2.0" --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)\netstandard2.0"

- task: PublishBuildArtifacts@1